### ISSUE TITLE
MIB error leaves an intermediate node unnamed

### ISSUE THREAD

**Issue by dnebeker** [masterzen/mysql-snmp#18]
The MIB file contains this definition:

mysql
::= { enterprises 20267 200 }

This ends up defining the object:

iso.org.dod.internet.private.enterprises.(??).mySQL

Instead the line should be something like:

::= { enterprises mySQLRoot(20267) 200 }

to give a name to the intermediate node.

**Comment by felipe-prenholato** [comment]
Fix proposed by @dnebeker also need to be done to create a pysnmp-mib file to use mysql-snmp with python.
