### ISSUE TITLE
MIB file with a lot of errors

### ISSUE THREAD

**Issue by felipe-prenholato** [masterzen/mysql-snmp#19]
I'm writing a python frontend for this snmp application, to store results and show graphs, however I can convert your mib to python because it have a lot of errors, and dont know how build mibs.

To see complete error list, go to http://www.simpleweb.org/ietf/mibs/validate/urls.php and put raw url from your mib, than submit.

**Comment by masterzen** [comment]
Well, I'm not a mib writer, so I'm not surprised :)
I'll try to fix that in a subsequent patch.

**Comment by felipe-prenholato** [comment]
I can do it, but need some orientation :)

Felipe 'chronos' Prenholato.
Linux User nº 405489
Home page: http://devwithpassion.com | http://chronosbox.org/blog
GitHub: http://github.com/chronossc/ | Twitter: http://twitter.com/chronossc

2012/11/22 Brice Figureau notifications@github.com

**Comment by masterzen** [comment]
This should fix all the validation errors and warnings.
Let me know if you still have difficulties to import the mib.
