### ISSUE TITLE
does not work on 64Bit machines :(

### ISSUE THREAD

**Issue by gmueller2000** [masterzen/mysql-snmp#2]
I am always getting:

2010-02-10 18:03:57,369 WARN  [DefaultUDPTransportMapping_127.0.0.1/0] SnmpNodeCollector: genErr collecting data for node 192.168.1.1: Received genErr reqeusting oid .1.3.6.1.4.1.20267.200.1.1. Marking column is finished.

**Comment by masterzen** [comment]
It definitely works on 64 bits machines (which is what I'm using).
Please check that:
- you're using SNMP v2c or v3
- it works with snmpwalk -v 2c from the opennms host

Things that are relevant to 64 bits problems are the snmp version on the host on which mysql-snmp is running. Make sure to use a version > 5.4.2.1.

Give me more details (including what gives snmpwalk, and the various versions of snmp and/or opennms) to help you find the issue.

**Comment by gmueller2000** [comment]
5.4.2.1. was my problem thank you

gerd

**Comment by masterzen** [comment]
re-open if you have any other issues
