### ISSUE TITLE
FreeBSD 8 Compatability

### ISSUE THREAD

**Issue by kbaegis** [masterzen/mysql-snmp#3]
The script doesn't appear to run on FreeBSD 8.  It doesn't return errors, and you can't find it under ps.  What information would you need to help me resolve this?  

FreeBSD 8.0 (amd64)
Perl 5.8.9
MySQL v14.14 D 5.1.46
NET-SNMP v5.6.dev
2ce4be9c4e114197756f025d3bffcfbafc396454 branch 'master' of git:/

**Comment by masterzen** [comment]
run the script as root from the command-line with -v --no-daemon.
This should print plenty of information on the console.
Note: I see you're running net-snmp 5.6.dev,, mysql-snmp was tested only on 5.4.X. Maybe they did change some APIs.

**Comment by kbaegis** [comment]
Thanks for the prompt reply.  The script seems to hang around the end of the polling:
Warning: Failed to connect to the agentx master agent ([NIL]): 
mysql-agent[62867]: not refreshing: 15 < 300

**Comment by masterzen** [comment]
Which means it can't access to the agentX socket of net-snmp.
Make sure:
- net-snmp is actually running, 
- net-snmp has agentX activated,
- net-snmp agentX socket is readable/writeable by the user running mysql-snmp

If you answered yes to all 3 questions above, then downgrade net-snmp to 5.4.2 or 5.5 to see if that helps.

**Comment by kbaegis** [comment]
I was a little worried about this.  Net-snmp uses inadequate regex to detect the operating system, breaking if-mib which cannot be disabled with command line configure flags.  Either that or FreeBSD uses an inconsistent naming convention, which is also possible I suppose.  In any case rolling back is not an option.  I'll see if I can ensure those three things manually.  :D

**Comment by kbaegis** [comment]
You were right to suspect that this wasn't your problem.  As it turns out I believe it was a parsing error in the configuration file performed by snmpd.  Thank you very much for your help.
