### ISSUE TITLE
Heads-up: mysql-snmp is getting packaged for FreeBSD

### ISSUE THREAD

**Issue by 0mp** [masterzen/mysql-snmp#31]
Hello,

I just wanted to let you know that I am working with the members of the FreeBSD community on adding mysql-snmp to the FreeBSD Ports Collection.

Here's a pending patch: https://reviews.freebsd.org/D22480

Reviews welcome!

**Comment by 0mp** [comment]
MySQL SNMP is now available in FreeBSD ports (https://www.freshports.org/net-mgmt/mysql-snmp/). The package can be installed via `pkg install mysql-snmp`. Cheers!

**Comment by masterzen** [comment]
Thank you very much for this work @0mp !

**Comment by 0mp** [comment]
Cheers! It was super useful to have the tests around: it was much easier to figure out the dependencies this way.

Also, FYI, the port was requested by Michael W Lucas in a post on the Fediverse: https://bsd.network/@mwlucas/103172585567158842
