### ISSUE TITLE
InnoDB data uninitialized

### ISSUE THREAD

**Issue by seattlegaucho** [masterzen/mysql-snmp#7]
I errors were variables "innodb_lsn" and "flushed_to" are initialized. Reviewing the server where I get this error I noticed that the only change is that it's using the InnoDB plugin with "Antelope" format and the SHOW ENGINE INNODB STATUS is not showing the lines:

[quote]
Log sequence number 9949124453266
Log flushed up to   9949124453266
Last checkpoint at  9949112672003
[/quote]

The difference between the servers is:

**\* FAILING:
show global variables like 'innodb_file_format%';
+--------------------------+-----------+
| Variable_name            | Value     |
+--------------------------+-----------+
| innodb_file_format       | Barracuda |
| innodb_file_format_check | Antelope  |
+--------------------------+-----------+

**\* WORKING:
show global variables like 'innodb_file_format%';
+--------------------------+-----------+
| Variable_name            | Value     |
+--------------------------+-----------+
| innodb_file_format       | Barracuda |
| innodb_file_format_check | Barracuda |
+--------------------------+-----------+

Notice the difference in 'innodb_file_format_check'.

I'm wondering if initializing both variables to 0 would get rid of the issue. Please advice.

Thanks,
G

**Comment by masterzen** [comment]
Thanks for the report. Can you send me the full SHOW ENGINE INNODB STATUS so that I can add more tests to mysql-snmp? What version of the plugin are you using?

**Comment by masterzen** [comment]
I believe the v1.2 fixes this issue. Please re-open if not.
